---
x-common: &common
  user: ${UID_GID}
  working_dir: /native
  environment:
    SCONS_CACHE: /scons-cache
  volumes:
    - .:/native
    - $SCONS_CACHE:/scons-cache

services:
  html5:
    <<: *common
    build:
      context: .
      dockerfile: javascript.Dockerfile
    command: ["sh", "-c", "scons platform=javascript target=template_$${TARGET:-debug}"]

  linux:
    <<: *common
    build:
      context: .
      dockerfile: linux.Dockerfile
    command: ["sh", "-c", "./build.sh --target $${TARGET:-debug}"]
